"""B4-Kitchen Eggs v0.1 replica execution for CMU Kitchen S13 Eggs.

Implements exactly docs/geometry/B3_KITCHEN_PREREG_EGGS_v0.1.md +
docs/geometry/PREREG_B4_KITCHEN_v0.3.md (statistical method, unchanged).

Reuses the geometry/audio extraction and Lambda-block construction logic
from core/b4_kitchen_run.py / b4_kitchen_run_v0_2.py UNCHANGED (same
Weingarten adapter, same RMSE-per-block audio reduction, same
triangulation file). The only things that differ from Brownie are: file
paths/names inside the archives, and the resulting frame/block counts
(a property of the data, computed and frozen in the manifest/prereg
BEFORE this script ran).

The statistical method is `ar1_effective_n_spearman` from
core/_kitchen_v03_candidate_methods_synthetic_only.py, copied here
UNCHANGED (frozen in PREREG_B4_KITCHEN_v0.3.md Section 2). Negative
control seeds are the ones frozen in
B3_KITCHEN_PREREG_EGGS_v0.1.md Section 5 (labels B4_KITCHEN_EGGS_NEG_X/Y),
generated by the identical rule as v0.3, before this script ever ran.

No analysis parameter in this file may be changed after seeing a result.
"""
from __future__ import annotations

import csv
import hashlib
import io
import json
import math
import multiprocessing
import sys
import wave
import zipfile
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
MOCAP_ARCHIVE = Path(r"C:\Users\jback\Downloads\S13_Eggs_Mocap.zip")
AUDIO_ARCHIVE = Path(r"C:\Users\jback\Downloads\S13_Eggs_Audio.zip")
MOCAP_MEMBER = "eggs_2.V.global"
TRIANGULATION = REPO / "docs" / "geometry" / "kitchen_triangulation.json"
RESULT_PATH = REPO / "docs" / "geometry" / "B4_KITCHEN_RESULT_EGGS_v0.1.json"
WINDOW_SIZE = 50
EPS = 1e-9
N_PERMUTATIONS = 10_000
SEED = 20_260_919
ALPHA = 0.05
GEOMETRY_WORKERS = 4
# Frozen in B3_KITCHEN_PREREG_EGGS_v0.1.md Section 1/3, BEFORE any geometry
# was read from this archive.
EXPECTED_MOCAP_ROWS = 58_509  # data rows in eggs_2.V.global, header excluded
LAST_AMC_FRAME = 58_508  # explicit last frame index in eggs_2.AMC
EXPECTED_N_GEOMETRY_FRAMES = 58_507  # frames 1..58507 (frame 0 and last excluded)
EXPECTED_N_BLOCKS = 1171  # ceil(58507 / 50), frozen in the manifest
_WORKER_FACES: np.ndarray | None = None


def _init_geometry_worker(faces: np.ndarray) -> None:
    global _WORKER_FACES
    sys.path.insert(0, str(REPO / "TIMDR-Geometry-Formalism"))
    _WORKER_FACES = faces


def _one_h(points: np.ndarray) -> float:
    # Repository's frozen Weingarten adapter, unchanged from Brownie.
    from timdr_geometry.geometry_meta_alignment import mesh_snapshot_to_mean_curvature
    from timdr_geometry.weingarten import Mesh

    volume = abs(float(np.linalg.det(np.stack((points[1] - points[0], points[2] - points[0], points[3] - points[0]))) / 6.0))
    if not np.all(np.isfinite(points)) or volume <= 1e-10:
        raise ValueError("invalid frozen geometry")
    if _WORKER_FACES is None:
        raise RuntimeError("geometry worker is not initialized")
    return mesh_snapshot_to_mean_curvature(Mesh(points, _WORKER_FACES))


def _seconds(value: str) -> float:
    hour, minute, second, fraction = value.split("_")
    return int(hour) * 3600 + int(minute) * 60 + int(second) + int(fraction) / 1e7


def _lambda(values: np.ndarray) -> float:
    values = np.asarray(values, dtype=float)
    if values.ndim != 1 or values.size == 0 or not np.all(np.isfinite(values)):
        raise ValueError("invalid Lambda input")
    std = float(np.std(values))
    mean = float(np.mean(values))
    return std / (std + abs(mean) + EPS)


def _rank(values: np.ndarray) -> np.ndarray:
    order = np.argsort(values, kind="mergesort")
    ranks = np.empty(values.size, dtype=float)
    ranks[order] = np.arange(values.size, dtype=float)
    sorted_values = values[order]
    start = 0
    while start < values.size:
        end = start + 1
        while end < values.size and sorted_values[end] == sorted_values[start]:
            end += 1
        if end - start > 1:
            ranks[order[start:end]] = (start + end - 1) / 2.0
        start = end
    return ranks


def _ar1(n: int, phi: float, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    result = np.empty(n, dtype=float)
    result[0] = rng.normal()
    for i in range(1, n):
        result[i] = phi * result[i - 1] + rng.normal()
    return result


def ar1_effective_n_spearman(x: np.ndarray, y: np.ndarray) -> dict:
    """Frozen v0.3 method, copied UNCHANGED from
    core/_kitchen_v03_candidate_methods_synthetic_only.py."""
    rx = _rank(x)
    ry = _rank(y)
    rx_c = rx - rx.mean()
    ry_c = ry - ry.mean()
    n = rx.size
    denom = float(np.linalg.norm(rx_c) * np.linalg.norm(ry_c))
    rho = float(np.dot(rx_c, ry_c) / denom)

    def lag1_autocorr(v_c):
        num = float(np.dot(v_c[1:], v_c[:-1]))
        den = float(np.dot(v_c, v_c))
        return num / den if den > 0 else 0.0

    r1x = lag1_autocorr(rx_c)
    r1y = lag1_autocorr(ry_c)
    denom_eff = 1.0 + r1x * r1y
    n_eff = n * (1.0 - r1x * r1y) / denom_eff if denom_eff > 0 else n
    n_eff = max(n_eff, 3.0)
    t_stat = rho * math.sqrt((n_eff - 2) / max(1e-12, 1 - rho ** 2))
    pvalue = math.erfc(abs(t_stat) / math.sqrt(2.0))
    return {"rho": rho, "r1x": r1x, "r1y": r1y, "n_eff": n_eff, "t": t_stat, "pvalue": pvalue}


def _read_times() -> np.ndarray:
    with zipfile.ZipFile(MOCAP_ARCHIVE) as archive:
        lines = archive.read("mocapTime-sync.txt").decode("ascii").splitlines()
    values = []
    for line in lines:
        frame, stamp = line.split()
        if int(frame.split(":")[1]) != len(values) + 1:
            raise ValueError("non-contiguous source frame numbering")
        values.append(_seconds(stamp))
    return np.asarray(values, dtype=float)


def _read_vertices() -> np.ndarray:
    config = json.loads(TRIANGULATION.read_text(encoding="utf-8"))
    wanted = [column for vertex in config["vertices"] for column in vertex["coordinate_columns"]]
    with zipfile.ZipFile(MOCAP_ARCHIVE) as archive, archive.open(MOCAP_MEMBER) as raw:
        rows = csv.reader(line.decode("utf-8") for line in raw)
        header = [cell.strip().strip('"') for cell in next(rows)]
        indices = [header.index(name) for name in wanted]
        values = [np.asarray([float(row[index]) for index in indices], dtype=float).reshape(4, 3) for row in rows]
    if len(values) != EXPECTED_MOCAP_ROWS:
        raise ValueError(f"unexpected V.global row count: {len(values)}")
    # record 0 = AMC frame 0 (excluded, no timestamp); last row = LAST_AMC_FRAME
    # (excluded, no T_(i+1)). Keep rows 1..LAST_AMC_FRAME-1 inclusive.
    return np.asarray(values[1:LAST_AMC_FRAME], dtype=float)


def _read_q(times: np.ndarray) -> np.ndarray:
    with zipfile.ZipFile(AUDIO_ARCHIVE) as archive:
        blob = archive.read("AudioTrack.wav")
        sync = archive.read("recording-synch.log").decode("ascii")
    start_line = next(line for line in sync.splitlines() if "opened at:" in line)
    audio_start = _seconds(start_line.rsplit(":", 1)[1].strip())
    with wave.open(io.BytesIO(blob), "rb") as wav:
        if wav.getnchannels() != 1 or wav.getsampwidth() != 2 or wav.getframerate() != 44_100:
            raise ValueError("AudioTrack.wav does not match frozen audio format")
        samples = np.frombuffer(wav.readframes(wav.getnframes()), dtype="<i2").astype(float)
        fs = wav.getframerate()
    q = np.empty(times.size - 1, dtype=float)
    for i, (begin, end) in enumerate(zip(times[:-1], times[1:])):
        lo = math.ceil((begin - audio_start) * fs)
        hi = math.ceil((end - audio_start) * fs)
        if lo < 0 or hi > samples.size or hi <= lo:
            raise ValueError(f"invalid audio interval for source frame {i + 1}")
        q[i] = float(np.sqrt(np.mean(np.square(samples[lo:hi]))))
    return q


def _h_trace(vertices: np.ndarray) -> np.ndarray:
    faces = np.asarray(json.loads(TRIANGULATION.read_text(encoding="utf-8"))["faces"], dtype=int)
    context = multiprocessing.get_context("spawn")
    with ProcessPoolExecutor(
        max_workers=GEOMETRY_WORKERS,
        mp_context=context,
        initializer=_init_geometry_worker,
        initargs=(faces,),
    ) as pool:
        return np.asarray(list(pool.map(_one_h, vertices, chunksize=250)), dtype=float)


def _blocks(values: np.ndarray) -> np.ndarray:
    return np.asarray([_lambda(values[start : start + WINDOW_SIZE]) for start in range(0, values.size, WINDOW_SIZE)])


def _seed_from_label(label: bytes) -> int:
    return int(hashlib.sha256(label).hexdigest()[:8], 16) % 10_000_000


def _controls(n: int) -> dict[str, object]:
    # Labels frozen in B3_KITCHEN_PREREG_EGGS_v0.1.md Section 5, generated
    # BEFORE this script ever read any Eggs geometry/audio.
    seed_x = _seed_from_label(b"B4_KITCHEN_EGGS_NEG_X")
    seed_y = _seed_from_label(b"B4_KITCHEN_EGGS_NEG_Y")
    positive = np.arange(n, dtype=float)
    positive_test = ar1_effective_n_spearman(positive, positive)
    negative_test = ar1_effective_n_spearman(_ar1(n, 0.8, seed_x), _ar1(n, 0.8, seed_y))
    return {
        "positive": positive_test,
        "negative": negative_test,
        "passed": positive_test["pvalue"] < ALPHA and negative_test["pvalue"] >= ALPHA,
        "seed_x": seed_x,
        "seed_y": seed_y,
    }


def main() -> None:
    times = _read_times()
    vertices = _read_vertices()
    if vertices.shape[0] != times.size - 1:
        raise ValueError("geometry/Q source-grid length mismatch")
    if vertices.shape[0] != EXPECTED_N_GEOMETRY_FRAMES:
        raise ValueError(f"unexpected frozen geometry frame count: {vertices.shape[0]}")
    q = _read_q(times)
    h = _h_trace(vertices)
    lambda_g, lambda_meta = _blocks(h), _blocks(q)
    if lambda_g.size != lambda_meta.size or lambda_g.size != EXPECTED_N_BLOCKS:
        raise ValueError(f"unexpected block count: {lambda_g.size} (expected {EXPECTED_N_BLOCKS})")
    controls = _controls(lambda_g.size)
    if not controls["passed"]:
        verdict = "INCONCLUSIVE"
        main_test = None
    else:
        main_test = ar1_effective_n_spearman(lambda_g, lambda_meta)
        verdict = "SUPPORTED" if main_test["pvalue"] < ALPHA else "NOT SUPPORTED"
    report = {
        "dataset_id": "CMU_KITCHEN_S13_EGGS_v0.1",
        "replica_of": "CMU_KITCHEN_S13_BROWNIE_v0.1 (same subject, different recipe)",
        "prereg": "docs/geometry/B3_KITCHEN_PREREG_EGGS_v0.1.md",
        "method": "ar1_effective_n_spearman (frozen unchanged from PREREG_B4_KITCHEN_v0.3.md)",
        "verdict": verdict,
        "n_geometry_frames": int(h.size),
        "n_blocks": int(lambda_g.size),
        "h_summary": {"min": float(h.min()), "max": float(h.max()), "mean": float(h.mean())},
        "q_summary": {"min": float(q.min()), "max": float(q.max()), "mean": float(q.mean())},
        "lambda_g_summary": {"min": float(lambda_g.min()), "max": float(lambda_g.max()), "mean": float(lambda_g.mean())},
        "lambda_meta_summary": {"min": float(lambda_meta.min()), "max": float(lambda_meta.max()), "mean": float(lambda_meta.mean())},
        "controls": controls,
        "main_test": main_test,
        "alpha": ALPHA,
    }
    RESULT_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2), flush=True)


if __name__ == "__main__":
    main()
